# Numpy 101

## What is numpy?

- python을 위한 array 연산 package
- 거의 모든 과학 연산 package의 기본 package

<center>
<img src="./img/chp0/numpy-support-pkg.png" alt="numpy-support-pkg" width="600"/>

*numpy가 지원하는 package (numpy가 직접 지원하지 않아도 잘 사용되는 package도 많음)*
</center>

- Python list와 numpy array의 다른 점
    - 고정된 크기로 생성된다: pop(element 제거),append(element 추가)와 같은 함수 사용의 overhead는 커지지만 계산 overhead가 크게 줄어듦
    - 모든 element가 같은 type을 가진다: list는 각 element마다 type check를 해야하는 overhead가 있지만, numpy array는 그런 시간이 줄어든다
    - 위와 같은 overhead와 data 규칙성을 제공하여 더 높은 수준의 최적화를 가능케 한다.
    - 행렬연산 함수를 지원한다.

## 설치 방법
Python이 이미 설치되어 있다는 가정하에 아래 명령어 중 하나를 실행한다.
```
conda install numpy 
```
or
```
pip install numpy
```

In [4]:
# package 호출 방법
import numpy as np

In [5]:
'''
numpy array 생성 방법
- array-like 데이터를 변환하는 방법
- 특수 함수를 사용하는 방법
'''
def print_all(array):
    print(array,f'shape: {array.shape}, data type: {array.dtype}')

print("1. array-like 데이터를 변환")
a = np.array([[1,2,3],[4,5,6]],dtype=int) # list 
print_all(a)
b = np.array(a,dtype=float) # np.ndarray
print_all(b)

print("2. 특수 함수를 사용")
a = np.random.rand(2,3)
print_all(a)
b = np.eye(3)
print_all(b)



1. array-like 데이터를 변환
[[1 2 3]
 [4 5 6]] shape: (2, 3), data type: int32
[[1. 2. 3.]
 [4. 5. 6.]] shape: (2, 3), data type: float64
2. 특수 함수를 사용
[[0.22095662 0.93615718 0.35105686]
 [0.95689898 0.90995835 0.94922042]] shape: (2, 3), data type: float64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] shape: (3, 3), data type: float64


In [9]:
a.nbytes * 8

384

위의 결과에서 data type이 단순한 int/float가 아닌 int32/float64임을 볼수 있다.

numpy array는 각 type을 표현할 bit 개수까지 정한다.
<center>
<img src="./img/chp0/int32.png" alt="numpy-support-pkg" width="600"/>
</center>

Quiz) np.ones((3,2),dtype=np.int32)가 차지하는 bit 개수를 생각해보자. 아래 python 코드를 돌리면 답을 확인할 수 있다.
```
a = np.ones((3,2),dtype=np.int32)
ans = a.nbytes * 8 # 1byte = 8bit
print(ans)
```